apiVersion: apps/v1
kind: Deployment
namespace: my-namespace
metadata:
  name: example-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: example-container
          image: nginx:1.17
